//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntertainPro
{


    public partial class AdminMovies
    {
        protected global::System.Web.UI.WebControls.Repeater rptMovies;
        protected global::System.Web.UI.WebControls.HiddenField hfMovieIdToDelete;
        protected global::System.Web.UI.WebControls.TextBox txtTitle;
        protected global::System.Web.UI.WebControls.TextBox txtGenre;
        protected global::System.Web.UI.WebControls.DropDownList ddlCategory;
        protected global::System.Web.UI.WebControls.DropDownList ddlSubCategory;
        protected global::System.Web.UI.WebControls.TextBox txtDuration;
        protected global::System.Web.UI.WebControls.TextBox txtLanguage;
        protected global::System.Web.UI.WebControls.TextBox txtRating;
        protected global::System.Web.UI.WebControls.TextBox txtTrailerUrl;
        protected global::System.Web.UI.WebControls.TextBox txtReleaseDate;
        protected global::System.Web.UI.WebControls.FileUpload ImageFile;
        protected global::System.Web.UI.WebControls.Button btnAddMovie;
        protected global::System.Web.UI.WebControls.Label lblValidationMessage;
    }
}
