//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntertainPro
{


    public partial class AdminDashboard
    {
        protected global::System.Web.UI.WebControls.Label lblTotalRevenue;
        protected global::System.Web.UI.WebControls.Label lblRevenueChange;
        protected global::System.Web.UI.WebControls.Label lblTicketsSold;
        protected global::System.Web.UI.WebControls.Label lblTicketsChange;
        protected global::System.Web.UI.WebControls.Label lblActiveUsers;
        protected global::System.Web.UI.WebControls.Label lblUsersChange;
        protected global::System.Web.UI.WebControls.Label lblMoviesPlaying;
        protected global::System.Web.UI.WebControls.Label lblMoviesChange;
        protected global::System.Web.UI.WebControls.Repeater rptRecentBookings;
    }
}
