//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntertainPro
{


    public partial class AdminTheaters
    {
        /// <summary>
        /// rptScreens control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater rptScreens;

        /// <summary>
        /// addScreenForm control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl addScreenForm;

        /// <summary>
        /// txtScreenName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtScreenName;

        /// <summary>
        /// ddlScreenType control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlScreenType;

        /// <summary>
        /// txtCapacity control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtCapacity;

        /// <summary>
        /// lblValidation control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblValidation;

        /// <summary>
        /// txtDescription control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtDescription;

        /// <summary>
        /// txtClassic control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtClassic;

        /// <summary>
        /// txtPrime control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtPrime;

        /// <summary>
        /// txtRecliner control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtRecliner;

        /// <summary>
        /// btnSaveScreen control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSaveScreen;

        protected global::System.Web.UI.WebControls.HiddenField hiddenDeleteId;

    }
}
