//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntertainPro
{


    public partial class AdminUsers
    {
        protected global::System.Web.UI.WebControls.Repeater UserRepeater;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl totalUsers;
        protected global::System.Web.UI.WebControls.HiddenField HiddenUserID;
    }
}
